order_management:
  enabled: true
  default_order_type: "limit"  # Options: market, limit, stop-limit
  default_slippage: 0.5  # Max slippage in % allowed
  allow_partial_fills: true  # Allow partial order fills
  max_open_orders: 10  # Maximum concurrent open orders
  retries: 3  # Number of retry attempts on failure
  notification:
    enabled: true
    channels: ["email", "telegram"]